### ISSUE TITLE
exemple with no Startover time available

### ISSUE THREAD

**Issue by emmanuelbaudet** [bertrandmartel/caipy-dashboard#33]
Please find below the link  sohing the use case : https://bertrandmartel.github.io/caipy-dashboard/?mode=live&apiUrl=****************************&startDate=21%2F08%2F2017&endDate=23%2F08%2F2017&dropProgram=900000&startOverDetectAd=660000&startOverDetectSharpStart=1200000&currentTime=1503401867864&windowStart=1503396150000&windowEnd=1503403350000&channel=TF1&preset=pods.

In that use case no startover time is provided, probably a bug or out of the cases described in the flow chart..

**Comment by bertrandmartel** [comment]
@emmanuelbaudet  It gives a correct startover value when I open the link 

![startover](https://user-images.githubusercontent.com/5183022/29818176-6a1dbe24-8cbb-11e7-90e4-75fb8ab35900.png)

**Comment by bertrandmartel** [comment]
@emmanuelbaudet note that I don't manage yet startover without ad maybe thats the mode you are using

**Comment by emmanuelbaudet** [comment]
Bertrand, 

C'est probablement un problème sur le mode play. Dans mon cas je n'avais aucun start over contrairement à l'image que tu viens de me donner. D'ailleurs les paramètres marge avant et marge arrière sont-ils transmis dans le share du start over ? 

Merci à toi.

Emmanuel

**Comment by bertrandmartel** [comment]
Le probleme est le mode without advertisement 
![withoutad](https://user-images.githubusercontent.com/5183022/29844568-060b7d2c-8d10-11e7-8ebf-6b532320c082.png)
